<?include('head.phtml')?>
<a class="button" href="<?=$url('/cms/post/add')?>">Add new</a>

<?if(true || $vars->posts):?>
  <?foreach($vars->posts as $post):?>
    <div class="post">
      <h2><a href="<?=$url('/cms/post/edit/' . $post->getId())?>"><?=$post->getTitle()?> <span class="admindate"><?=$post->getHumanDate()?></span> &raquo;</a></h2>
    </div>
  <?endforeach?>
<?else:?>
  <p>No Posts yet</p>
<?endif?>

<?include('foot.phtml')?>