<!DOCTYPE html>
<html>
  <head>
    <title><?=$vars->title?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="<?=$url('/css/style.css')?>"/>
    <link rel="stylesheet" type="text/css" href="<?=$url('/css/user.css')?>"/>
  </head>
  <body>
    <div id="main">
      <h1 class="title"><?=$vars->title?></h1>
      <div id="posts">