<?include('head.phtml')?>

<?if(@$vars->post['id']):?>
<form action="<?=$url('/cms/post/edit/' . $vars->post['id'])?>" method="post">
<?else:?>
<form action="<?=$url('/cms/post/add')?>" method="post">
<?endif?>
  <label for="title">Title:</label>
  <input type="text" name="title" value="<?=@$vars->post['title']?>"/>
  <label for="content">Article:</label><textarea name="content"><?=@$vars->post['content']?></textarea>
  <label>&nbsp;</label><input type="submit" value="Save"/>
</form>

<a href="<?=$url('/cms')?>">&laquo; Back to list</a>

<?include('foot.phtml')?>