<?include('head.phtml')?>

<?if(@$vars->post['id']):?>
<form action="<?=$url('/cms/post/edit/' . $vars->post['id'])?>" method="post">
<?else:?>
<form action="<?=$url('/cms/post/add')?>" method="post">
<?endif?>
  <a href="<?=$url('/cms')?>">&laquo; Back to list</a><a class="submit" href="#">Save &raquo</a>
  <div class="clear"></div>
  <br>
  <input type="text" name="name"
         placeholder="Url chunk here"
         value="<?=@$vars->post['name']?>"/>
  <input type="text" name="title"
         placeholder="Title here"
         value="<?=@$vars->post['title']?>"/>
  <textarea name="content" placeholder="Article here"><?=@$vars->post['content']?></textarea>
</form>

<?include('foot.phtml')?>